<<<<<<< HEAD
#sky:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    host: localhost
#    port: 3306
#    database: sky_take_out
#    username: root
#    password: yaoheyiyhy
#
=======
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yaoheyiyhy

>>>>>>> 0f072ba3d2d02569e1f4491320f94ea9a1d01214
#  alioss:
#    bucket-name: yhy-com
#    endpoint: oss-cn-beijing.aliyuncs.com
#    access-key-secret: LTAI5t6gg5cGvqDALivRBWer
#    access-key-id: LTAI5t6gg5cGvqDALivRBWer
#
#  redis:
#    host: localhost
#    port: 6379
#    password: yaoheyiyhy
#    database: 10
#
#  wechat:
#    appid: wxae56fd7d3a75390c
#    secret: 0322f6df4af9b0bd6ad359010f69f23f
